version: '3.5'

services:
  nodejs:
    build:
      context: ./node-js/
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-nodejs
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://mashup:password@database:5432/mashup
    ports:
      - 3001:3000
    container_name: backend-mashup-nodejs
  
  rust:
    build:
      context: ./rust/
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-rust
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://mashup:password@database:5432/mashup
    ports:
      - 3002:3000
    container_name: backend-mashup-rust
  
  rust-poem:
    build:
      context: ./rust-poem/
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-rust-poem
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://mashup:password@database:5432/mashup
    ports:
      - 3003:3003
    container_name: backend-mashup-rust-poem
  
  python-flask:
    build:
      context: ./python-flask/services/web
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:server
    image: xneme/backend-mashup-python-flask
    depends_on:
      - database
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://mashup:password@database:5432/mashup
    ports:
      - 3004:5000
    container_name: backend-mashup-python-flask

  java-spring:
    build: 
      context: ./java-spring
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-java-spring
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mashup
      - SPRING_DATASOURCE_USERNAME=mashup
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 3005:8080
    container_name: backend-mashup-java-spring

  go-fiber:
    build:
      context: ./go-fiber
      dockerfile: ./Dockerfile
    command: go run cmd/main.go cmd/routes.go -b 0.0.0.0
    image: xneme/backend-mashup-go-fiber
    depends_on:
      - database
    environment:
      - DB_DSN=host=database user=mashup password=password port=5432 sslmode=disable TimeZone=Europe/Helsinki
    ports:
      - 3006:3000
    container_name: backend-mashup-go-fiber

  haskell-scotty:
    build:
      context: ./haskell-scotty
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-haskell-scotty
    depends_on:
      - database
    ports:
      - 3007:3000
    container_name: backend-mashup-haskell-scotty
  
  cpp-pistache:
    build:
      context: ./cpp-pistache
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-cpp-pistache
    depends_on:
      - database
    environment:
      - DB_DSN=host=database user=mashup password=password port=5432 sslmode=disable TimeZone=Europe/Helsinki
    ports:
      - 3008:3000
    container_name: backend-mashup-cpp-pistache
  
  database:
    image: postgres:14.3
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    ports:
      - 5432:5432
    container_name: backend-mashup-database

volumes:
  pg_data:
