version: '3.5'

services:
  nodejs:
    build:
      context: ./node-js/
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-nodejs
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://mashup:password@database:5432/mashup
    ports:
      - 3001:3000
    container_name: backend-mashup-nodejs
  
  rust:
    build:
      context: ./rust/
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-rust
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://mashup:password@database:5432/mashup
    ports:
      - 3002:3000
    container_name: backend-mashup-rust
  
  rust-poem:
    build:
      context: ./rust-poem/
      dockerfile: ./Dockerfile
    image: xneme/backend-mashup-rust-poem
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://mashup:password@database:5432/mashup
    ports:
      - 3003:3003
    container_name: backend-mashup-rust-poem
  
  database:
    image: postgres:14.3
    environment:
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/data
    ports:
      - 5432:5432
    container_name: backend-mashup-database

volumes:
  pg_data:
